### ISSUE TITLE
not compiling on windows 

### ISSUE THREAD

**Issue by alas82** [GuvaCode/UnRecord#1]
hello , thanks for the program , can you help us to use it on windows , i think some units missing?

**Comment by GuvaCode** [comment]
yes, you are absolutely right. it doesn't work under windows yet.
I'll fix it soon

**Comment by GuvaCode** [comment]
> hello , thanks for the program , can you help us to use it on windows , i think some units missing?

I have added windows support. but there was one bug, the icons are not displayed. We need to look for where the error is.

![prev](https://github.com/GuvaCode/UnRecord/assets/18312729/fad7d0ea-fea2-42f3-ae48-3cca08ab19c0)

**Comment by alas82** [comment]
Thanks for fixing it, you are right the icons disappeared.

**Comment by GuvaCode** [comment]
> Thanks for fixing it, you are right the icons disappeared.

Bug with icons in windows is fixed

![prev](https://github.com/GuvaCode/UnRecord/assets/18312729/fbbb55ed-f309-4176-bf6a-68d5a9532c6c)
